//! LightCraft desktop app.
//!
//! Usage: `lightcraft [--library DIR | --memory] [--no-demo] [--control <port>] [files or folders…]`
//!
//! The library (catalog, presets, thumbnail cache) lives in `--library DIR`, else
//! `$LIGHTCRAFT_LIBRARY`, else the library last opened with Settings → Open Library…, else
//! `~/Pictures/LightCraft Library`; a new library starts with the
//! procedural demo photos unless `--no-demo` or files are given. Files and folders on the command
//! line are imported (duplicates are skipped). `--memory` runs an in-memory session that writes
//! nothing (demo photos unless files are given; used by the README showcase scripts). A library
//! that can't be opened is never replaced silently: the window says why and asks what to do
//! (`lightcraft_ui_egui::panels::library_problem`).
//!
//! `--control <port>` (or `LIGHTCRAFT_CONTROL_PORT`) starts a localhost JSON-lines control server:
//! `{"id":1,"method":"ui.inspect","params":{}}` → `{"id":1,"ok":true,"result":…}`.
//! See `lightcraft_ui_egui::control` for the methods.
//!
//! On Windows, release builds are GUI-subsystem programs: launching the app opens no console
//! window (issue #7). Their `--help` / `--version` output and diagnostics then have no console to
//! go to; use `lightcraft-cli` (a console program) from a terminal, or a debug build.
#![cfg_attr(all(target_os = "windows", not(debug_assertions)), windows_subsystem = "windows")]
#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::unimplemented, clippy::todo, clippy::unreachable)]

mod control_server;
#[cfg(target_os = "macos")]
mod native_menu;

use lightcraft_embed::alloc_release;
use lightcraft_embed::prefs::{PrefsWriter, config_dir, load_prefs};
use lightcraft_embed::services::services;
use lightcraft_embed::session::{configure_segmenter, open_session};
use lightcraft_ui_egui::LightcraftApp;

/// Reverse-DNS app id: Wayland app id, `.desktop` file and hicolor icon name.
const APP_ID: &str = "ai.storyteller.lightcraft";

/// The window, taskbar and Dock icon (assets/app-icon/, regenerated by packaging/icons.sh). macOS
/// gets the version with Apple's transparent margin so it sits right among the other Dock icons.
fn app_icon() -> egui::IconData {
    #[cfg(target_os = "macos")]
    let png: &[u8] = include_bytes!("../../../assets/app-icon/lightcraft-macos-512.png");
    #[cfg(not(target_os = "macos"))]
    let png: &[u8] = include_bytes!("../../../assets/app-icon/hicolor/256x256/apps/ai.storyteller.lightcraft.png");
    eframe::icon_data::from_png_bytes(png).unwrap_or_default()
}

struct App(LightcraftApp, PrefsWriter, #[cfg(target_os = "macos")] Option<native_menu::NativeMenu>);

impl eframe::App for App {
    fn logic(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        #[cfg(target_os = "macos")]
        if let Some(m) = self.2.as_mut() {
            m.update(&mut self.0, ctx);
        }
        self.0.logic(ctx);
        self.1.tick(&mut self.0, ctx);
    }
    fn raw_input_hook(&mut self, _ctx: &egui::Context, raw: &mut egui::RawInput) {
        self.0.raw_input_hook(raw);
    }
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        self.0.ui(ui);
    }
    fn on_exit(&mut self) {
        if let Err(e) = self.1.save(&self.0) {
            eprintln!("lightcraft: {e}");
        }
        if let Err(e) = self.0.session.close_library() {
            eprintln!("lightcraft: saving the library failed: {e}");
        }
    }
}

/// The window's renderer (egui-wgpu): eframe's defaults, with LightCraft's backend choice — DX12
/// alone on Windows unless `LIGHTCRAFT_GPU_BACKEND` / `WGPU_BACKEND` say otherwise (issue #136:
/// with Vulkan in the set, wgpu loads the Vulkan driver even when it then picks DX12).
fn window_wgpu_options() -> eframe::egui_wgpu::WgpuConfiguration {
    let mut c = eframe::egui_wgpu::WgpuConfiguration::default();
    if let eframe::egui_wgpu::WgpuSetup::CreateNew(n) = &mut c.wgpu_setup {
        n.instance_descriptor.backends = lightcraft_engine::gpu::backend::window_backends();
    }
    c
}

/// Written while the GPU compute device is created, removed once that returned
/// (`lightcraft_gpu::backend::set_init_marker`). Not with `LIGHTCRAFT_NO_PREFS` (tests, scripts).
fn gpu_marker_path() -> Option<std::path::PathBuf> {
    if std::env::var_os("LIGHTCRAFT_NO_PREFS").is_some() {
        return None;
    }
    config_dir().map(|d| d.join("gpu-init.marker"))
}

/// Arm the GPU crash sentinel; if the previous launch left it behind (it died inside the GPU
/// driver while creating the device), the notice to show — GPU rendering then starts off.
fn gpu_crash_check() -> Option<String> {
    let marker = gpu_marker_path();
    let left = marker.as_deref().and_then(lightcraft_engine::gpu::backend::take_init_marker);
    lightcraft_engine::gpu::backend::set_init_marker(marker);
    left.map(|what| gpu_crash_notice(&what))
}

fn gpu_crash_notice(what: &str) -> String {
    format!(
        "LightCraft closed unexpectedly while starting the GPU last time ({what}), so GPU rendering is now off and photos render on the CPU. \
         To try the GPU again, turn on Settings ▸ Performance ▸ Use the GPU for rendering; to try another graphics backend, start LightCraft with \
         LIGHTCRAFT_GPU_BACKEND=dx12, vulkan or off (see docs/gpu-pipeline.md → Troubleshooting)."
    )
}

const HELP: &str = "\
lightcraft — photo library + raw developer

USAGE: lightcraft [OPTIONS] [FILES/FOLDERS…]   (files and folders are imported)

OPTIONS:
  --library DIR    open (or create) this library (default: ~/Pictures/LightCraft Library; env LIGHTCRAFT_LIBRARY)
  --no-demo        don't seed a new library with the procedural demo photos
  --memory         throwaway in-memory session (alias --demo); nothing is saved
  --control PORT   serve the JSON-lines control channel on 127.0.0.1:PORT (env LIGHTCRAFT_CONTROL_PORT;
                   see docs/control-protocol.md)
  --version, --help

ENVIRONMENT:
  LIGHTCRAFT_GPU_BACKEND=dx12|vulkan|metal|auto|off   graphics backend (default: DX12 on Windows, Metal on macOS,
                   Vulkan on Linux; off = render on the CPU); else WGPU_BACKEND. LIGHTCRAFT_GPU=0: CPU rendering.
  LIGHTCRAFT_SAM3_DIR=DIR   the SAM 3 model for Object / Describe masks (default: <settings folder>/models/sam3;
                   optional: LightCraft offers to download it when first needed)
  LIGHTCRAFT_SAM3_MIRRORS=URL,…   where to download the SAM 3 model from (base URLs, tried in order)
";

/// Warnings and errors (failed commands, AI mask analysis) on stderr; `LIGHTCRAFT_LOG=info`
/// (or `debug`) shows more.
struct StderrLog(log::LevelFilter);

impl log::Log for StderrLog {
    fn enabled(&self, m: &log::Metadata) -> bool {
        m.level() <= self.0 && (m.level() <= log::Level::Warn || m.target().starts_with("lightcraft"))
    }
    fn log(&self, r: &log::Record) {
        if self.enabled(r.metadata()) {
            eprintln!("lightcraft: {} {}: {}", r.level(), r.target(), r.args());
        }
    }
    fn flush(&self) {}
}

fn install_log() {
    let level = match std::env::var("LIGHTCRAFT_LOG").unwrap_or_default().as_str() {
        "debug" => log::LevelFilter::Debug,
        "info" => log::LevelFilter::Info,
        _ => log::LevelFilter::Warn,
    };
    static LOGGER: std::sync::OnceLock<StderrLog> = std::sync::OnceLock::new();
    if log::set_logger(LOGGER.get_or_init(|| StderrLog(level))).is_ok() {
        log::set_max_level(level);
    }
}

fn main() -> eframe::Result {
    lightcraft_engine::guard::install_hook(lightcraft_engine::paths::data_root().unwrap_or_else(std::env::temp_dir).join("lightcraft-panics.log"));
    install_log();
    alloc_release::install();
    let mut control_port: Option<u16> = std::env::var("LIGHTCRAFT_CONTROL_PORT").ok().and_then(|p| p.parse().ok());
    let mut files = Vec::new();
    let mut seed_demo = true;
    let mut in_memory = false;
    let mut library_dir: Option<std::path::PathBuf> = None;
    let mut args = std::env::args().skip(1);
    while let Some(a) = args.next() {
        match a.as_str() {
            "--control" => control_port = args.next().and_then(|p| p.parse().ok()),
            "--library" => library_dir = args.next().map(std::path::PathBuf::from),
            "--no-demo" => seed_demo = false,
            "--memory" | "--demo" => in_memory = true,
            "--version" => {
                println!("lightcraft {}", env!("CARGO_PKG_VERSION"));
                return Ok(());
            }
            "-h" | "--help" => {
                print!("{HELP}");
                return Ok(());
            }
            o if o.starts_with("--") => {
                eprintln!("lightcraft: unknown option `{o}`\n\n{HELP}");
                std::process::exit(2);
            }
            _ => files.push(a),
        }
    }
    let (prefs, prefs_warning, keep_prefs_file) = load_prefs();
    // --library, else the library last opened from Settings, else the default location
    let library_dir = library_dir.or_else(|| lightcraft_embed::session::library_dir(prefs.as_ref()));
    // GPU compute: off if the preference says so, or if the last launch died creating the device
    // (issue #136) — before anything can create it
    let gpu_crash = gpu_crash_check();
    let gpu_on = prefs.as_ref().is_none_or(|u| u.settings.gpu) && gpu_crash.is_none();
    lightcraft_engine::gpu::set_enabled(gpu_on);
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_title("LightCraft")
            .with_inner_size([1600.0, 1000.0])
            .with_min_inner_size([900.0, 560.0])
            .with_drag_and_drop(true)
            .with_fullsize_content_view(true)
            .with_titlebar_shown(false)
            .with_title_shown(false)
            .with_icon(app_icon())
            // Wayland matches the window to packaging/linux/ai.storyteller.lightcraft.desktop by this id
            .with_app_id(APP_ID),
        wgpu_options: window_wgpu_options(),
        ..Default::default()
    };
    eframe::run_native(
        "LightCraft",
        options,
        Box::new(move |cc| {
            let (mut session, problem) = open_session(in_memory, library_dir, seed_demo && files.is_empty());
            configure_segmenter(&mut session);
            let mut app = LightcraftApp::new(session, services());
            if let Some(ui) = prefs {
                app.ui = ui;
            }
            lightcraft_ui_egui::i18n::set_language(app.ui.language);
            app.integrated_titlebar = cfg!(target_os = "macos");
            app.notices.extend(prefs_warning);
            // what's on disk now: only changes are written
            let writer = PrefsWriter::new(&app, keep_prefs_file);
            // after the snapshot above, so the writer saves the switched-off preference
            if let Some(notice) = gpu_crash {
                app.ui.settings.gpu = false;
                app.notices.push(notice);
            }
            if let Some(port) = control_port {
                let rx = control_server::start(port, cc.egui_ctx.clone());
                app = app.with_control(rx);
            }
            if let Some(mut p) = problem {
                // imported once the user has chosen where (into the library, or the temporary session)
                p.pending_import = files;
                app.library_problem = Some(p);
            } else if !files.is_empty() {
                let _ = app.run("library.import", serde_json::json!({"paths": files}));
                app.ui.view = lightcraft_ui_egui::state::ViewMode::PhotoGrid;
            }
            // native menu bar generated from the command registry (macOS; elsewhere the menus are
            // drawn in the window's top bar). LIGHTCRAFT_NO_NATIVE_MENU=1 keeps the in-window menus.
            #[cfg(target_os = "macos")]
            let menu = (std::env::var_os("LIGHTCRAFT_NO_NATIVE_MENU").is_none()).then(|| native_menu::NativeMenu::install(&mut app, &cc.egui_ctx));
            Ok(Box::new(App(
                app,
                writer,
                #[cfg(target_os = "macos")]
                menu,
            )))
        }),
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    fn dir(tag: &str) -> std::path::PathBuf {
        let d = std::env::temp_dir().join(format!("lc-app-prefs-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    /// Issue #136: a GPU init marker left by a crashed launch is reported once and removed.
    #[test]
    fn gpu_crash_marker_is_reported_once() {
        let d = dir("gpu-marker");
        let m = d.join("gpu-init.marker");
        assert_eq!(lightcraft_engine::gpu::backend::take_init_marker(&m), None);
        std::fs::write(&m, "GPU device creation started (backends VULKAN | DX12)").unwrap();
        let what = lightcraft_engine::gpu::backend::take_init_marker(&m).unwrap();
        let notice = gpu_crash_notice(&what);
        assert!(notice.contains("GPU rendering is now off") && notice.contains("Use the GPU for rendering"), "{notice}");
        assert!(!m.exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    /// Issue #136: Windows windows render with DX12 alone (no Vulkan driver loaded) by default.
    #[test]
    fn window_backends_follow_the_platform_default() {
        let eframe::egui_wgpu::WgpuSetup::CreateNew(n) = window_wgpu_options().wgpu_setup else { panic!("expected CreateNew") };
        let b = n.instance_descriptor.backends;
        if std::env::var_os("LIGHTCRAFT_GPU_BACKEND").is_none() && std::env::var_os("WGPU_BACKEND").is_none() {
            if cfg!(windows) {
                assert_eq!(b, eframe::wgpu::Backends::DX12);
            } else if cfg!(target_os = "macos") {
                assert_eq!(b, eframe::wgpu::Backends::METAL);
            }
        }
        assert!(!b.is_empty());
    }
}
